version: "3.9"
services:
  rstudio:
    image: "$US_ELECTRICITY_IMAGE" 
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "$US_ELECTRICITY_DIR"
        target: "/home/rstudio"
      - type: "bind"
        source: "$RSTUDIO_CONFIG_PATH"
        target: "/home/rstudio/.config/rstudio"
    environment:
      EIA_API_KEY: $EIA_API_KEY